apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fil-rouge-prod
nameSuffix: -prod

resources:
  - ../../base
  - pdb.yaml

labels:
  - includeSelectors: false
    pairs:
      env: prod

replicas:
  - name: notes-api
    count: 3
  - name: notes-web
    count: 2

images:
  - name: localhost:5001/notes-api
    newTag: "2.0.0"

configMapGenerator:
  - name: notes-config
    behavior: merge
    literals:
      - APP_GREETING=PRODUCTION
      - APP_COLOR=#c53030

patches:
  - path: ressources-patch.yaml
    target:
      kind: Deployment
      name: notes-api
  - target:
      kind: Ingress
      name: notes
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prod.127.0.0.1.nip.io
replacements:
  # Nom réel du Service de la base -> DB_HOST de l'API
  - source:
      kind: Service
      name: notes-db
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: notes-api
        fieldPaths:
          - spec.template.spec.containers.[name=api].env.[name=DB_HOST].value

  # Nom réel du Service de l'API -> API_UPSTREAM du frontend ("<nom>:8000")
  - source:
      kind: Service
      name: notes-api
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: notes-web
        fieldPaths:
          - spec.template.spec.containers.[name=web].env.[name=API_UPSTREAM].value
        options:
          delimiter: ':'      # on ne remplace que la partie avant ':'
          index: 0            # "notes-api:8000" -> "notes-api-dev:8000"
